K3S_IP = "192.168.56.110"
HOSTS = {
  "app1.com" => K3S_IP,
  "app2.com" => K3S_IP,
  "app3.com" => K3S_IP
}

Vagrant.configure("2") do |config|

    #SSH configuration
    config.ssh.insert_key = true
    # Define the server (1-st virtual machine)
    config.vm.define "tmazitovS" do |server|
    
        # General Settings
        # + Initial image (Ubuntu 24.04)
        # + Hostname
        # + Shared folder for files transfer
        server.vm.box = "bento/ubuntu-24.04"  # initial image of the 
        server.vm.hostname = "tmazitovS" # name of vm
        server.vm.synced_folder ".", "/vagrant" # shared folder setup
    
        # Network
        # + Host:80 -> VM:8000
        # + Add to public network with specified IP address
        # server.vm.network "forwarded_port", guest: 80, host: 8080
        server.vm.network "private_network", ip: K3S_IP
    
        # Provider Settings (VirtualBox)
        # + 512mb RAM
        # + 1 core CPU
        server.vm.provider "qemu" do |qe|
            qe.memory = "2048"
            vb.cpus = 2
        end
    
        # Provision Settings (Initialization commands)
        server.vm.provision "shell", inline: <<-SHELL
            apt-get update
            apt-get install -y curl
        SHELL

        # server_worker.vm.provision "shell"
        server.vm.provision "shell", path: "scripts/server-provisioning.sh"
    end

    config.trigger.after :up do |trigger|
    trigger.info = "Configuring local /etc/hosts..."

    trigger.run = {
        inline: "bash scripts/update-hosts.sh"
    }
    end
end